### PR TITLE
fixed Karl, added auto test suite, and more resolution test

### PR DESCRIPTION
**Pull request by doutriaux1**
also fastened triple loop for grid gen

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 was there a plan to conda-erise this?

**Comment by doutriaux1** [comment]
@durack1 I think we should...

**Comment by durack1** [comment]
@doutriaux1 it certainly would make testing, and updating ALOT easier.. I tried to install a week ago, and hit problems

**Comment by doutriaux1** [comment]
@durack1 I can't work on this today, but please file an issue so we do not forget.

**Pull request merged**
